package com.appsdeveloperblog.app.ws.mobileappws.Enum;

public enum ProductCategory {
SUPERMARKET, HEALTH_BEAUTY, HOME_OFFICE, PHONE_TABLET,COMPUTING, ELECTRONICS,FASHION,BABY_PRODUCTS, GAMING, SPORTING_GOODS,
    AUTOMOBILE
}
